name: SQL Server

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Abstractions/**'
      - 'DistributedLocking/**'
      - 'Repositories/SqlServer/**/**'
  workflow_dispatch:
    

jobs:
  integration-tests-sql-server:

    runs-on: ubuntu-latest
    
    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env: 
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong(!)Password
        ports:
          - 1433:1433

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        # comma separated list of XML/JSON/YAML files in which tokens are to be substituted. Files names must be specified relative to the folder-path.
        files: 'Repositories/SqlServer/Tests/DistributedLocking.SqlServer.IntegrationTests/appsettings.json'
      env:
        SqlServerDistributedLockConfiguration.ConnectionString: "Server=localhost;Database=master;User ID=sa;Password=yourStrong(!)Password"
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --filter DistributedLocking.SqlServer.IntegrationTests
